<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('provincias', function (Blueprint $table) {
            $table->increments('idProv'); // AUTO_INCREMENT y PK
            $table->string('Provincia', 50);
            $table->integer('idDepa')->unsigned(); // solo referencia, sin FK
        });

        // Insertar registros iniciales (solo primeros para ejemplo)
        DB::table('provincias')->insert([

['idProv' => 1, 'Provincia' => 'CHACHAPOYAS', 'idDepa' => 1],
['idProv' => 2, 'Provincia' => 'BAGUA', 'idDepa' => 1],
['idProv' => 3, 'Provincia' => 'BONGARA', 'idDepa' => 1],
['idProv' => 4, 'Provincia' => 'CONDORCANQUI', 'idDepa' => 1],
['idProv' => 5, 'Provincia' => 'LUYA', 'idDepa' => 1],
['idProv' => 6, 'Provincia' => 'RODRIGUEZ DE MENDOZA', 'idDepa' => 1],
['idProv' => 7, 'Provincia' => 'UTCUBAMBA', 'idDepa' => 1],
['idProv' => 8, 'Provincia' => 'HUARAZ', 'idDepa' => 2],
['idProv' => 9, 'Provincia' => 'AIJA', 'idDepa' => 2],
['idProv' => 10, 'Provincia' => 'ANTONIO RAYMONDI', 'idDepa' => 2],
['idProv' => 11, 'Provincia' => 'ASUNCION', 'idDepa' => 2],
['idProv' => 12, 'Provincia' => 'BOLOGNESI', 'idDepa' => 2],
['idProv' => 13, 'Provincia' => 'CARHUAZ', 'idDepa' => 2],
['idProv' => 14, 'Provincia' => 'CARLOS FERMIN FITZCARRALD', 'idDepa' => 2],
['idProv' => 15, 'Provincia' => 'CASMA', 'idDepa' => 2],
['idProv' => 16, 'Provincia' => 'CORONGO', 'idDepa' => 2],
['idProv' => 17, 'Provincia' => 'HUARI', 'idDepa' => 2],
['idProv' => 18, 'Provincia' => 'HUARMEY', 'idDepa' => 2],
['idProv' => 19, 'Provincia' => 'HUAYLAS', 'idDepa' => 2],
['idProv' => 20, 'Provincia' => 'MARISCAL LUZURIAGA', 'idDepa' => 2],
['idProv' => 21, 'Provincia' => 'OCROS', 'idDepa' => 2],
['idProv' => 22, 'Provincia' => 'PALLASCA', 'idDepa' => 2],
['idProv' => 23, 'Provincia' => 'POMABAMBA', 'idDepa' => 2],
['idProv' => 24, 'Provincia' => 'RECUAY', 'idDepa' => 2],
['idProv' => 25, 'Provincia' => 'SANTA', 'idDepa' => 2],
['idProv' => 26, 'Provincia' => 'SIHUAS', 'idDepa' => 2],
['idProv' => 27, 'Provincia' => 'YUNGAY', 'idDepa' => 2],
['idProv' => 28, 'Provincia' => 'ABANCAY', 'idDepa' => 3],
['idProv' => 29, 'Provincia' => 'ANDAHUAYLAS', 'idDepa' => 3],
['idProv' => 30, 'Provincia' => 'ANTABAMBA', 'idDepa' => 3],
['idProv' => 31, 'Provincia' => 'AYMARAES', 'idDepa' => 3],
['idProv' => 32, 'Provincia' => 'COTABAMBAS', 'idDepa' => 3],
['idProv' => 33, 'Provincia' => 'CHINCHEROS', 'idDepa' => 3],
['idProv' => 34, 'Provincia' => 'GRAU', 'idDepa' => 3],
['idProv' => 35, 'Provincia' => 'AREQUIPA', 'idDepa' => 4],
['idProv' => 36, 'Provincia' => 'CAMANA', 'idDepa' => 4],
['idProv' => 37, 'Provincia' => 'CARAVELI', 'idDepa' => 4],
['idProv' => 38, 'Provincia' => 'CASTILLA', 'idDepa' => 4],
['idProv' => 39, 'Provincia' => 'CAYLLOMA', 'idDepa' => 4],
['idProv' => 40, 'Provincia' => 'CONDESUYOS', 'idDepa' => 4],
['idProv' => 41, 'Provincia' => 'ISLAY', 'idDepa' => 4],
['idProv' => 42, 'Provincia' => 'LA UNION', 'idDepa' => 4],
['idProv' => 43, 'Provincia' => 'HUAMANGA', 'idDepa' => 5],
['idProv' => 44, 'Provincia' => 'CANGALLO', 'idDepa' => 5],
['idProv' => 45, 'Provincia' => 'HUANCA SANCOS', 'idDepa' => 5],
['idProv' => 46, 'Provincia' => 'HUANTA', 'idDepa' => 5],
['idProv' => 47, 'Provincia' => 'LA MAR', 'idDepa' => 5],
['idProv' => 48, 'Provincia' => 'LUCANAS', 'idDepa' => 5],
['idProv' => 49, 'Provincia' => 'PARINACOCHAS', 'idDepa' => 5],
['idProv' => 50, 'Provincia' => 'PAUCAR DEL SARA SARA', 'idDepa' => 5],
['idProv' => 51, 'Provincia' => 'SUCRE', 'idDepa' => 5],
['idProv' => 52, 'Provincia' => 'VICTOR FAJARDO', 'idDepa' => 5],
['idProv' => 53, 'Provincia' => 'VILCAS HUAMAN', 'idDepa' => 5],
['idProv' => 54, 'Provincia' => 'CAJAMARCA', 'idDepa' => 6],
['idProv' => 55, 'Provincia' => 'CAJABAMBA', 'idDepa' => 6],
['idProv' => 56, 'Provincia' => 'CELENDIN', 'idDepa' => 6],
['idProv' => 57, 'Provincia' => 'CHOTA', 'idDepa' => 6],
['idProv' => 58, 'Provincia' => 'CONTUMAZA', 'idDepa' => 6],
['idProv' => 59, 'Provincia' => 'CUTERVO', 'idDepa' => 6],
['idProv' => 60, 'Provincia' => 'HUALGAYOC', 'idDepa' => 6],
['idProv' => 61, 'Provincia' => 'JAEN', 'idDepa' => 6],
['idProv' => 62, 'Provincia' => 'SAN IGNACIO', 'idDepa' => 6],
['idProv' => 63, 'Provincia' => 'SAN MARCOS', 'idDepa' => 6],
['idProv' => 64, 'Provincia' => 'SAN PABLO', 'idDepa' => 6],
['idProv' => 65, 'Provincia' => 'SANTA CRUZ', 'idDepa' => 6],
['idProv' => 66, 'Provincia' => 'CALLAO', 'idDepa' => 7],
['idProv' => 67, 'Provincia' => 'CUSCO', 'idDepa' => 8],
['idProv' => 68, 'Provincia' => 'ACOMAYO', 'idDepa' => 8],
['idProv' => 69, 'Provincia' => 'ANTA', 'idDepa' => 8],
['idProv' => 70, 'Provincia' => 'CALCA', 'idDepa' => 8],
['idProv' => 71, 'Provincia' => 'CANAS', 'idDepa' => 8],
['idProv' => 72, 'Provincia' => 'CANCHIS', 'idDepa' => 8],
['idProv' => 73, 'Provincia' => 'CHUMBIVILCAS', 'idDepa' => 8],
['idProv' => 74, 'Provincia' => 'ESPINAR', 'idDepa' => 8],
['idProv' => 75, 'Provincia' => 'LA CONVENCION', 'idDepa' => 8],
['idProv' => 76, 'Provincia' => 'PARURO', 'idDepa' => 8],
['idProv' => 77, 'Provincia' => 'PAUCARTAMBO', 'idDepa' => 8],
['idProv' => 78, 'Provincia' => 'QUISPICANCHI', 'idDepa' => 8],
['idProv' => 79, 'Provincia' => 'URUBAMBA', 'idDepa' => 8],
['idProv' => 80, 'Provincia' => 'HUANCAVELICA', 'idDepa' => 9],
['idProv' => 81, 'Provincia' => 'ACOBAMBA', 'idDepa' => 9],
['idProv' => 82, 'Provincia' => 'ANGARAES', 'idDepa' => 9],
['idProv' => 83, 'Provincia' => 'CASTROVIRREYNA', 'idDepa' => 9],
['idProv' => 84, 'Provincia' => 'CHURCAMPA', 'idDepa' => 9],
['idProv' => 85, 'Provincia' => 'HUAYTARA', 'idDepa' => 9],
['idProv' => 86, 'Provincia' => 'TAYACAJA', 'idDepa' => 9],
['idProv' => 87, 'Provincia' => 'HUANUCO', 'idDepa' => 10],
['idProv' => 88, 'Provincia' => 'AMBO', 'idDepa' => 10],
['idProv' => 89, 'Provincia' => 'DOS DE MAYO', 'idDepa' => 10],
['idProv' => 90, 'Provincia' => 'HUACAYBAMBA', 'idDepa' => 10],
['idProv' => 91, 'Provincia' => 'HUAMALIES', 'idDepa' => 10],
['idProv' => 92, 'Provincia' => 'LEONCIO PRADO', 'idDepa' => 10],
['idProv' => 93, 'Provincia' => 'MARA&Ntilde;ON', 'idDepa' => 10],
['idProv' => 94, 'Provincia' => 'PACHITEA', 'idDepa' => 10],
['idProv' => 95, 'Provincia' => 'PUERTO INCA', 'idDepa' => 10],
['idProv' => 96, 'Provincia' => 'LAURICOCHA', 'idDepa' => 10],
['idProv' => 97, 'Provincia' => 'YAROWILCA', 'idDepa' => 10],
['idProv' => 98, 'Provincia' => 'ICA', 'idDepa' => 11],
['idProv' => 99, 'Provincia' => 'CHINCHA', 'idDepa' => 11],
['idProv' => 100, 'Provincia' => 'NAZCA', 'idDepa' => 11],
['idProv' => 101, 'Provincia' => 'PALPA', 'idDepa' => 11],
['idProv' => 102, 'Provincia' => 'PISCO', 'idDepa' => 11],
['idProv' => 103, 'Provincia' => 'HUANCAYO', 'idDepa' => 12],
['idProv' => 104, 'Provincia' => 'CONCEPCION', 'idDepa' => 12],
['idProv' => 105, 'Provincia' => 'CHANCHAMAYO', 'idDepa' => 12],
['idProv' => 106, 'Provincia' => 'JAUJA', 'idDepa' => 12],
['idProv' => 107, 'Provincia' => 'JUNIN', 'idDepa' => 12],
['idProv' => 108, 'Provincia' => 'SATIPO', 'idDepa' => 12],
['idProv' => 109, 'Provincia' => 'TARMA', 'idDepa' => 12],
['idProv' => 110, 'Provincia' => 'YAULI', 'idDepa' => 12],
['idProv' => 111, 'Provincia' => 'CHUPACA', 'idDepa' => 12],
['idProv' => 112, 'Provincia' => 'TRUJILLO', 'idDepa' => 13],
['idProv' => 113, 'Provincia' => 'ASCOPE', 'idDepa' => 13],
['idProv' => 114, 'Provincia' => 'BOLIVAR', 'idDepa' => 13],
['idProv' => 115, 'Provincia' => 'CHEPEN', 'idDepa' => 13],
['idProv' => 116, 'Provincia' => 'JULCAN', 'idDepa' => 13],
['idProv' => 117, 'Provincia' => 'OTUZCO', 'idDepa' => 13],
['idProv' => 118, 'Provincia' => 'PACASMAYO', 'idDepa' => 13],
['idProv' => 119, 'Provincia' => 'PATAZ', 'idDepa' => 13],
['idProv' => 120, 'Provincia' => 'SANCHEZ CARRION', 'idDepa' => 13],
['idProv' => 121, 'Provincia' => 'SANTIAGO DE CHUCO', 'idDepa' => 13],
['idProv' => 122, 'Provincia' => 'GRAN CHIMU', 'idDepa' => 13],
['idProv' => 123, 'Provincia' => 'VIRU', 'idDepa' => 13],
['idProv' => 124, 'Provincia' => 'CHICLAYO', 'idDepa' => 14],
['idProv' => 125, 'Provincia' => 'FERRE&Ntilde;AFE', 'idDepa' => 14],
['idProv' => 126, 'Provincia' => 'LAMBAYEQUE', 'idDepa' => 14],
['idProv' => 127, 'Provincia' => 'LIMA', 'idDepa' => 15],
['idProv' => 128, 'Provincia' => 'BARRANCA', 'idDepa' => 15],
['idProv' => 129, 'Provincia' => 'CAJATAMBO', 'idDepa' => 15],
['idProv' => 130, 'Provincia' => 'CANTA', 'idDepa' => 15],
['idProv' => 131, 'Provincia' => 'CA&Ntilde;ETE', 'idDepa' => 15],
['idProv' => 132, 'Provincia' => 'HUARAL', 'idDepa' => 15],
['idProv' => 133, 'Provincia' => 'HUAROCHIRI', 'idDepa' => 15],
['idProv' => 134, 'Provincia' => 'HUAURA', 'idDepa' => 15],
['idProv' => 135, 'Provincia' => 'OYON', 'idDepa' => 15],
['idProv' => 136, 'Provincia' => 'YAUYOS', 'idDepa' => 15],
['idProv' => 137, 'Provincia' => 'MAYNAS', 'idDepa' => 16],
['idProv' => 138, 'Provincia' => 'ALTO AMAZONAS', 'idDepa' => 16],
['idProv' => 139, 'Provincia' => 'LORETO', 'idDepa' => 16],
['idProv' => 140, 'Provincia' => 'MARISCAL RAMON CASTILLA', 'idDepa' => 16],
['idProv' => 141, 'Provincia' => 'REQUENA', 'idDepa' => 16],
['idProv' => 142, 'Provincia' => 'UCAYALI', 'idDepa' => 16],
['idProv' => 143, 'Provincia' => 'TAMBOPATA', 'idDepa' => 17],
['idProv' => 144, 'Provincia' => 'MANU', 'idDepa' => 17],
['idProv' => 145, 'Provincia' => 'TAHUAMANU', 'idDepa' => 17],
['idProv' => 146, 'Provincia' => 'MARISCAL NIETO', 'idDepa' => 18],
['idProv' => 147, 'Provincia' => 'GENERAL SANCHEZ CERRO', 'idDepa' => 18],
['idProv' => 148, 'Provincia' => 'ILO', 'idDepa' => 18],
['idProv' => 149, 'Provincia' => 'PASCO', 'idDepa' => 19],
['idProv' => 150, 'Provincia' => 'DANIEL ALCIDES CARRION', 'idDepa' => 19],
['idProv' => 151, 'Provincia' => 'OXAPAMPA', 'idDepa' => 19],
['idProv' => 152, 'Provincia' => 'PIURA', 'idDepa' => 20],
['idProv' => 153, 'Provincia' => 'AYABACA', 'idDepa' => 20],
['idProv' => 154, 'Provincia' => 'HUANCABAMBA', 'idDepa' => 20],
['idProv' => 155, 'Provincia' => 'MORROPON', 'idDepa' => 20],
['idProv' => 156, 'Provincia' => 'PAITA', 'idDepa' => 20],
['idProv' => 157, 'Provincia' => 'SULLANA', 'idDepa' => 20],
['idProv' => 158, 'Provincia' => 'TALARA', 'idDepa' => 20],
['idProv' => 159, 'Provincia' => 'SECHURA', 'idDepa' => 20],
['idProv' => 160, 'Provincia' => 'PUNO', 'idDepa' => 21],
['idProv' => 161, 'Provincia' => 'AZANGARO', 'idDepa' => 21],
['idProv' => 162, 'Provincia' => 'CARABAYA', 'idDepa' => 21],
['idProv' => 163, 'Provincia' => 'CHUCUITO', 'idDepa' => 21],
['idProv' => 164, 'Provincia' => 'EL COLLAO', 'idDepa' => 21],
['idProv' => 165, 'Provincia' => 'HUANCANE', 'idDepa' => 21],
['idProv' => 166, 'Provincia' => 'LAMPA', 'idDepa' => 21],
['idProv' => 167, 'Provincia' => 'MELGAR', 'idDepa' => 21],
['idProv' => 168, 'Provincia' => 'MOHO', 'idDepa' => 21],
['idProv' => 169, 'Provincia' => 'SAN ANTONIO DE PUTINA', 'idDepa' => 21],
['idProv' => 170, 'Provincia' => 'SAN ROMAN', 'idDepa' => 21],
['idProv' => 171, 'Provincia' => 'SANDIA', 'idDepa' => 21],
['idProv' => 172, 'Provincia' => 'YUNGUYO', 'idDepa' => 21],
['idProv' => 173, 'Provincia' => 'MOYOBAMBA', 'idDepa' => 22],
['idProv' => 174, 'Provincia' => 'BELLAVISTA', 'idDepa' => 22],
['idProv' => 175, 'Provincia' => 'EL DORADO', 'idDepa' => 22],
['idProv' => 176, 'Provincia' => 'HUALLAGA', 'idDepa' => 22],
['idProv' => 177, 'Provincia' => 'LAMAS', 'idDepa' => 22],
['idProv' => 178, 'Provincia' => 'MARISCAL CACERES', 'idDepa' => 22],
['idProv' => 179, 'Provincia' => 'PICOTA', 'idDepa' => 22],
['idProv' => 180, 'Provincia' => 'RIOJA', 'idDepa' => 22],
['idProv' => 181, 'Provincia' => 'SAN MARTIN', 'idDepa' => 22],
['idProv' => 182, 'Provincia' => 'TOCACHE', 'idDepa' => 22],
['idProv' => 183, 'Provincia' => 'TACNA', 'idDepa' => 23],
['idProv' => 184, 'Provincia' => 'CANDARAVE', 'idDepa' => 23],
['idProv' => 185, 'Provincia' => 'JORGE BASADRE', 'idDepa' => 23],
['idProv' => 186, 'Provincia' => 'TARATA', 'idDepa' => 23],
['idProv' => 187, 'Provincia' => 'TUMBES', 'idDepa' => 24],
['idProv' => 188, 'Provincia' => 'CONTRALMIRANTE VILLAR', 'idDepa' => 24],
['idProv' => 189, 'Provincia' => 'ZARUMILLA', 'idDepa' => 24],
['idProv' => 190, 'Provincia' => 'CORONEL PORTILLO', 'idDepa' => 25],
['idProv' => 191, 'Provincia' => 'ATALAYA', 'idDepa' => 25],
['idProv' => 192, 'Provincia' => 'PADRE ABAD', 'idDepa' => 25],
['idProv' => 193, 'Provincia' => 'PURUS', 'idDepa' => 25],
            
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('provincias');
    }
};
